.TH "_rijndael_ctx" 3 "Fri Jul 19 2013" "Version 1" "libfortuna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_rijndael_ctx \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rijndael\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBu4byte\fP \fBk_len\fP"
.br
.ti -1c
.RI "int \fBdecrypt\fP"
.br
.ti -1c
.RI "\fBu4byte\fP \fBe_key\fP [64]"
.br
.ti -1c
.RI "\fBu4byte\fP \fBd_key\fP [64]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBu4byte\fP _rijndael_ctx::d_key[64]"

.SS "int _rijndael_ctx::decrypt"

.SS "\fBu4byte\fP _rijndael_ctx::e_key[64]"

.SS "\fBu4byte\fP _rijndael_ctx::k_len"


.SH "Author"
.PP 
Generated automatically by Doxygen for libfortuna from the source code\&.
