.TH "BlowfishContext" 3 "Fri Jul 19 2013" "Version 1" "libfortuna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlowfishContext \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <blf\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint32\fP \fBS0\fP [256]"
.br
.ti -1c
.RI "\fBuint32\fP \fBS1\fP [256]"
.br
.ti -1c
.RI "\fBuint32\fP \fBS2\fP [256]"
.br
.ti -1c
.RI "\fBuint32\fP \fBS3\fP [256]"
.br
.ti -1c
.RI "\fBuint32\fP \fBP\fP [18]"
.br
.ti -1c
.RI "\fBuint32\fP \fBiv0\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBiv1\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint32\fP BlowfishContext::iv0"

.SS "\fBuint32\fP BlowfishContext::iv1"

.SS "\fBuint32\fP BlowfishContext::P[18]"

.SS "\fBuint32\fP BlowfishContext::S0[256]"

.SS "\fBuint32\fP BlowfishContext::S1[256]"

.SS "\fBuint32\fP BlowfishContext::S2[256]"

.SS "\fBuint32\fP BlowfishContext::S3[256]"


.SH "Author"
.PP 
Generated automatically by Doxygen for libfortuna from the source code\&.
