.TH "c.h" 3 "Fri Jul 19 2013" "Version 1" "libfortuna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
c.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef signed char \fBint8\fP"
.br
.ti -1c
.RI "typedef signed short \fBint16\fP"
.br
.ti -1c
.RI "typedef signed int \fBint32\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBuint8\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBuint16\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBuint32\fP"
.br
.ti -1c
.RI "typedef \fBuint8\fP \fBbits8\fP"
.br
.ti -1c
.RI "typedef \fBuint16\fP \fBbits16\fP"
.br
.ti -1c
.RI "typedef \fBuint32\fP \fBbits32\fP"
.br
.ti -1c
.RI "typedef long int \fBint64\fP"
.br
.ti -1c
.RI "typedef unsigned long int \fBuint64\fP"
.br
.ti -1c
.RI "typedef \fBint16\fP \fBint2\fP"
.br
.ti -1c
.RI "typedef \fBint32\fP \fBint4\fP"
.br
.ti -1c
.RI "typedef float \fBfloat4\fP"
.br
.ti -1c
.RI "typedef double \fBfloat8\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBuint16\fP \fBbits16\fP"

.SS "typedef \fBuint32\fP \fBbits32\fP"

.SS "typedef \fBuint8\fP \fBbits8\fP"

.SS "typedef float \fBfloat4\fP"

.SS "typedef double \fBfloat8\fP"

.SS "typedef signed short \fBint16\fP"

.SS "typedef \fBint16\fP \fBint2\fP"

.SS "typedef signed int \fBint32\fP"

.SS "typedef \fBint32\fP \fBint4\fP"

.SS "typedef long int \fBint64\fP"

.SS "typedef signed char \fBint8\fP"

.SS "typedef unsigned short \fBuint16\fP"

.SS "typedef unsigned int \fBuint32\fP"

.SS "typedef unsigned long int \fBuint64\fP"

.SS "typedef unsigned char \fBuint8\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for libfortuna from the source code\&.
