.TH "error_desc" 3 "Fri Jul 19 2013" "Version 1" "libfortuna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
error_desc \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBerr\fP"
.br
.ti -1c
.RI "const char * \fBdesc\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "const char* error_desc::desc"

.SS "int error_desc::err"


.SH "Author"
.PP 
Generated automatically by Doxygen for libfortuna from the source code\&.
