.TH "fortuna.h" 3 "Fri Jul 19 2013" "Version 1" "libfortuna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fortuna.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'c\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfortuna_get_bytes\fP (unsigned len, \fBuint8\fP *dst)"
.br
.ti -1c
.RI "void \fBfortuna_add_entropy\fP (const \fBuint8\fP *data, unsigned len)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void fortuna_add_entropy (const \fBuint8\fP *data, unsignedlen)"

.SS "void fortuna_get_bytes (unsignedlen, \fBuint8\fP *dst)"

.SH "Author"
.PP 
Generated automatically by Doxygen for libfortuna from the source code\&.
