.TH "int_cipher" 3 "Fri Jul 19 2013" "Version 1" "libfortuna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
int_cipher \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBPX_Cipher\fP *(* \fBload\fP )(void)"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBPX_Cipher\fP*(* int_cipher::load)(void)"

.SS "char* int_cipher::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for libfortuna from the source code\&.
