.TH "int_digest" 3 "Fri Jul 19 2013" "Version 1" "libfortuna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
int_digest \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "void(* \fBinit\fP )(\fBPX_MD\fP *h)"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void(* int_digest::init)(\fBPX_MD\fP *h)"

.SS "char* int_digest::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for libfortuna from the source code\&.
