.TH "px_alias" 3 "Fri Jul 19 2013" "Version 1" "libfortuna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
px_alias \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <px\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBalias\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char* px_alias::alias"

.SS "char* px_alias::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for libfortuna from the source code\&.
